### ISSUE TITLE
[question] Is there currently a way to disable a "resource pack prompt" using the config for the buttons?

### ISSUE THREAD

**Issue by koalalord9999** [Shadows-of-Fire/PackMenu#18]
I'm usign a modpack that has some buttons that directly connect to the server I play on, and it doesn't let me change the option to never prompt for a resource pack. I already have it manually installed on my client, and don't need to reload it every time I log in. Is this a possibel config option to disable in the buttons? Thanks :)

**Comment by Shadows-of-Fire** [comment]
There is not, and it might take a bit to solve, since normally the server data is serialized as part of the multiplayer list, but with the packmenu direct connect button action, that server data object is never serialized.  The resource pack mode will probably have to be manually stored somewhere else so that it's not permanently in prompt mode.

**Comment by Shadows-of-Fire** [comment]
Solved by creating a dummy ServerData to hold the RP prompt info inside.
