### ISSUE TITLE
[Feature Request] Additional states for ICON and TEXT

### ISSUE THREAD

**Issue by Ridanisaurus** [Shadows-of-Fire/PackMenu#51]
The addition of additional states to the ICON and TEXT objects would allow for better visual effects such as a new texture, or an X + Y position.
It can follow the same 4 states of the SPRITE object.

**Comment by Shadows-of-Fire** [comment]
Fortunately I think we only need two states (not hovered/focused and hovered/focused) because the `disabled` state is static for the lifetime of the button.  The only reason the `WidgetSprites` object has the four states at the json level is because it's a vanilla object, and "real" buttons may have all four states.
